### ISSUE TITLE
Problem running the example

### ISSUE THREAD

**Issue by npalacioescat** [mathiaskalxdorf/IceR#1]
**Describe the bug**
Running the example described in the README with the provided example data fails.

**To Reproduce**
1. Loaded the IceR with `library(IceR)`
2. Opened the GUI with `runIceR()`
3. Set up the pointers to the directories where the raw and MaxQuant data were downloaded
4. Reduced number of cores to 4 as described in the README
5. Left all other parameters to default values (see below)

**Expected behavior**
To be able to reproduce the example without errors

**Traceback**
```R
Loading required package: shiny

Listening on http://127.0.0.1:3538
[1] "2021-02-05 10:41:40 Job started"
[1] "2021-02-05 10:41:40 Preparation finished"
[1] "2021-02-05 10:41:40 Raw file conversion finished"
[1] "2021-02-05 10:41:40 Preparation of mzXMLs finished"
[1] "Read MaxQ results"
[1] "Read MaxQ results finished"
[1] "Prepare for peptide feature matching - Indexing all ions"
[1] "Train RF models for mz-corrections"
[1] "20200110_QE1_DDA_1H25_T5_E9_R1: R^2 train-set=0.95, R^2 eval-set=0.94"
[1] "2021-02-05 10:53:10 Feature alignmend finished"
[1] "Added 18798 isotope features."
[1] "2021-02-05 10:53:11 Addition of +1 isotope features finished"
Warning: Error in colnames<-: attempt to set 'colnames' on an object with less than two dimensions
  2: shiny::runApp
  1: runIceR
```

**Log file**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 7 Professional SP1
 - R version: 4.0.3
 - ProteoWizard version: 3.0.18247.49b14bb3d
 - Version or commit hash: d802b33

**Additional context**
Parameter file:
```
Settings_name | Setting
-- | --
Path to raw files | F:/IceR_example/Raw_files/
Path to MaxQ results | F:/IceR_example/MaxQ_results
Path to results | F:/IceR_example/IceR_example_results
Analysis name | IceR_example
mz_window |  
RT_window |  
min_mz_window | 0.001
min_RT_window | 1
feature_mass_deviation_collapse | 0.002
only_unmodified_peptides | FALSE
align_unknown | FALSE
use_isotope_peaks | TRUE
peak_detection | TRUE
abundance_estimation_correction | TRUE
alignment_score_cut | 0.05
Quant_pVal_cut | 0.05
n_cores | 3
RT_correction | TRUE
mz_correction | TRUE
add_PMPs | FALSE
plot_peak_detection | FALSE
calc_protein_LFQ | TRUE
kde_resolution | 50
num_peaks_store | 5
MassSpec_mode | Orbitrap
use_IM_data | FALSE
Multiplicity | 1
Light_labels |  
Medium_labels |  
Heavy_labels |  
```

**Comment by mathiaskalxdorf** [comment]
Hi @Nic-Nic,

based on the traceback console log you reported, it looks like you only provided a single out of 4 raw files (example data set) to IceR
[1] "Train RF models for mz-corrections"
[1] "20200110_QE1_DDA_1H25_T5_E9_R1: R^2 train-set=0.95, R^2 eval-set=0.94"
IceR reports the results of the random forest model fittings for every sample individually so here you should see 4 instead of 1 line. Furthermore, I don´t see that IceR automatically triggered raw to mzxml conversion. Did you do this manually or was it done by IceR in a first attempt? If done manually, please check that (for your example path):
- still all raw files are found in in F:/IceR_example/Raw_files/
- all corresponding mzXML files with matching names (file names have to be identical between raw and mzxml files, only file extension should be different) are found in F:/IceR_example/Raw_files/mzXML

Can you check that all raw files are available in your specified folder? Please also cosider removing the Temporary_files folder in F:/IceR_example/IceR_example_results when you start IceR the next time to enable a fresh run.

The next release of IceR will also contain some additional warning messages if certain criteria are not met.
