### ISSUE TITLE
Error in `[<-.data.frame`(`*tmp*`, data_protein_peptide_count < min_pep_count.....

### ISSUE THREAD

**Issue by DickDekkers** [mathiaskalxdorf/IceR#11]
Hi Mathias,
When loading the MaxQuant data from my own dataset I get an error:
==============
> MaxQ <- load_MaxQ_data()
[1] "Select a file in the MaxQ output folder"
[1] "Selected path to MaxQuant output: D:\\___DATA_NOBACKUP\\Aniek_TurboID_selection\\combined\\txt\\"
Error in `[<-.data.frame`(`*tmp*`, data_protein_peptide_count < min_pep_count,  : 
  unsupported matrix index in replacement
==============

I also ran IceR test RAW files and that went well.
How can I solve this?

Thanks in advance for your reply.

Dick Dekkers

**Comment by mathiaskalxdorf** [comment]
Hi, 

this error can not be solved without more details. Which MaxQuant Version did you use? Can you check that all expected columns are available in your peptides.txt file by comparing against the supplied MaxQ results of the example data set? If you can not spot the issue, can you upload the proteinGroups.txt and peptides.txt somewhere so that I can have a look at the problem from my side?

Best,

Mathias

**Comment by DickDekkers** [comment]
Hi Mathias,
Thanks for your swift reply.
MaxQ version 2.0.1.0 has been used to generate my data. At first glance all data seems to be there. Compared to the supplied MaxQ data set my data has some new columns. This data is from an IP experiment and LFQ calculation has not been selected.
I have added the proteinGroups.txt and the peptides.txt files.
I would appreciate your help.

Best,
Dick
[peptides.txt](https://github.com/mathiaskalxdorf/IceR/files/7151963/peptides.txt)
[proteinGroups.txt](https://github.com/mathiaskalxdorf/IceR/files/7151964/proteinGroups.txt)

**Comment by mathiaskalxdorf** [comment]
Hi Dick,

I quickly checked it. The function load_MaxQ_data() by default expects LFQ quantifications to be available. However, in your data these columns are not available. Please select the right quantification column using the parameter intensity_used which can be one of the following "LFQ intensity" or "iBAQ" or "Intensity". In the next IceR version there will be a check that the selected quantification columns are actually available and otherwise reports a more suitable error message.

Best,

Mathias

**Comment by DickDekkers** [comment]
Hi Mathias,

Your suggestion worked but I am running into the next problem. 
My plan is now to use another sample set where I can use LFQ together with the MaxQ version you used.
What is the latest MaxQ version you used with IceR?

Best,
Dick

**Comment by mathiaskalxdorf** [comment]
Hi Dick,

I recently pushed a new version of IceR to the master and development branch (V0.9.10 and V1.2.0). I tested the development version with data from the latest MaxQuant version (V2.0.3.0) and it worked fine. Same should be true for the master version, however, I did not explicitly test it. So IceR should be compatible even with the latest MaxQuant version.

Best regards,

Mathias
