### ISSUE TITLE
Error: in  [.data frame: undefined columns selected

### ISSUE THREAD

**Issue by K-Boum** [mathiaskalxdorf/IceR#19]
Hey Mathias,

I am getting this error message after the imputation step. The log file is attached below.  
[Error_undefinedcolumns.xlsx](https://github.com/mathiaskalxdorf/IceR/files/7519586/Error_undefinedcolumns.xlsx)

Any help with that issue is highly appreciated!

On another note: Does IceR generate an "updated" output table (like the ProteinGorups table from MQ) that can be used for data analysis with  Perseus?

Best wishes,

Michal

**Comment by mathiaskalxdorf** [comment]
Hey,
can you check if the file "Quantification_raw_results_with_scores_filtered.RData" is properly saved. If yes, could you upload this file somewhere, so that I can check where the error is afterwards happening?
Regarding your question: IceR is reporting a new table with results, it is not "updating" MQ tables. Still, I think Perseus is flexible to read-in data in slightly different format than MQ results. So the IceR table contains Identifier, Gene name, and quantifications per sample (or quantifications per feature, depending on which output you are then using). I hope this would be still usable for you.

As a note: The peak selection FDR of IceR on your data does not look great (several >10%). That is a bit worrying. Do these samples show large and random retention-time variations between samples? Were these samples all measured on the same machine in a row? Or are there any batch effects known for these samples?

Best

**Comment by K-Boum** [comment]
Hey Mathias,

Thanks for the quick response!

These are fractionated samples so the variability comes from that. I am aware that IceR has not been tested for that, but I figured it might be worth trying.

You can find the file here:
https://boxup.uni-potsdam.de/s/TpxHp6RxBcyYg9a/download

Best

**Comment by K-Boum** [comment]
Hey Mathias,

Thanks for the quick response.

These are fractionated samples so the variability comes from that. I am aware that IceR has not been tested for that, but I figured it might be worth trying. 

You can find the file here: https://www.file-upload.net/download-14745784/Quantification_raw_results_with_scores_filtered.RData.html

**Comment by mathiaskalxdorf** [comment]
Thanks for the upload. 

Looks like the prepared data by IceR is fine. Hence, most likely the error occurs during the intensity correction step. To have a closer look into that I would need two more files which are stored by IceR in the "Temporary_files" folder within the specified IceR output folder. The two files are preprocess_quant.RData and id_mapping.RData. As I just recently updated the way how the preprocess quantification results are stored and incorporated into the IceR run, it is very likely that I just missed something in there causing the error which you received. Can you send me these files as well? They should be rather small.

Thanks a lot. These kinds of feedback are very useful to make IceR robust against potential problems which can just occur.

Best,

Mathias

**Comment by K-Boum** [comment]
I checked both computers but alas, the mentioned files are not in the Temporary files folder.

Best,
Michal

**Comment by mathiaskalxdorf** [comment]
Ok, then you are using a previous version of IceR. Can you update to the latest one and (as it is most advanced) use the development version? The installation can be done by devtools::install_github("mathiaskalxdorf/IceR",ref = "develop")
If the error disappears, then the bug was already solved with the latest update. If it is still crashing, then this time the two required files should be in the temporary files folder

**Comment by K-Boum** [comment]
I worked just fine with the new version. Thanks!

P.S. Will TMT be also supported in any future update?
