### ISSUE TITLE
MPI spawn error 

### ISSUE THREAD

**Issue by Monod79** [mathiaskalxdorf/IceR#21]
As I'm highly eager to implement this nice IceR pipeline, RMPI::mpi.comm.spawn raises an error during the scoring of alignment and quantification. 

![image](https://user-images.githubusercontent.com/52295327/156243714-b108a77b-66fb-4705-bf5f-e43b33d80a80.png)

IceR was run on R version 4.1.2. under Windows 10, with Rmpi package version  0.6-9.2. Microsoft MPI v 10.0 is installed. I would appreciate any help!

**Comment by mathiaskalxdorf** [comment]
Hey, I´m sorry to say that I most likely can not help with this error as it seems to be an error triggered not directly by the IceR code itself. Furthermore, I never saw this error before. I assume it is occurring when the threads for parallel processing are initiated during the scoring of the alignment and quantification, however, the exact same multithreading approach is used already several times before the step at which you get the error. This could indicate that it is a spontaneous error rather than a general issue. So, my suggestion would be to rerun IceR and see if the error is reoccurring or if it then runs through. I hope this solves the issue.

**Comment by Monod79** [comment]
Thanks Mathias. I reran the pipeline many times using different approaches/setting, but could never solve the issue. 

Please, could you provide me with the MPI (MPICH2 or Microsoft MPI) and RMPI versions you were using while testing IceR in Windows10? 

I tried to implement Rpmi's instructions (http://fisher.stats.uwo.ca/faculty/yu/Rmpi/), but I'm still hitting the wall...

**Comment by mathiaskalxdorf** [comment]
I checked on all the machines I use and used IceR. On none of them Rmpi is installed. I actually do not even see in the code where Rmpi should be required. Only possibility would be for the parallel processing in which case IceR uses the package doSNOW/snow. So as said, I can not help you with this issue. Furthermore, as IceR was getting for you until the "Scoring of alignment and quantification", it means that the parallel processing was working during the steps before. You could try to uninstall Rmpi and see if it is then working. I also do not see any installed MPI version on the Windows machines. Where is this getting from for you? Did you have this already previously installed? Similarly for Rmpi, did you manually install this before?

**Comment by Monod79** [comment]
That was really helpful Mathias. After removing the Rpmi package, the pipeline ran smoothly to completion. I guess IceR is calling a shared name function with Rpmi.

Many thanks for your help !

Jonathan
