### ISSUE TITLE
IceR finished or crashed?

### ISSUE THREAD

**Issue by WeiqiangChen** [mathiaskalxdorf/IceR#25]
library(IceR)
runIceR()   
# number of thread 23,
# raw files in mzxml format
# MaxQuant txt folder
# folder to write the result

IceR runs for some time and then it looks like crashed. But the console in Rstudio is still running. Nothing really happened even after left  the PC untouched over weekend. There is no apparent error. 

There are some generated files in the Temporary_files. But no Features_x.tab file could be found, which is requested by load_Requant_data().
Also, an updated proteingroups.txt file is nowhere to find. Where is the final output of IceR if it finished?

**Comment by mathiaskalxdorf** [comment]
Hey, can you please report the whole R console output? Otherwise it is rather difficult to find the issue. Thanks and best regards.

**Comment by WeiqiangChen** [comment]
I have tried IceR with another MaxQuant search result. This time it seems to be finished. with the following logs.

[1] "Finished LFQ-quantification (2022-10-03 12:49:46)"
Time difference of 2.777711 secs
[1] "2022-10-03 12:50:49 Protein-level aggregation finished"
[1] "2022-10-03 12:50:49 Store all results"
[1] "2022-10-03 12:51:06 Feature and protein quantification finished"
[1] "2022-10-03 12:51:06 Job finished"

Now there are 20 .tab files + Parameters.xlsx in the IceR output folder. 

How should I get the MaxQuant proteingroups.txt equivalent output file? 

 IceR <- load_Requant_data() is not working. Is my folder name too long?

> IceR <- load_Requant_data()
[1] "Select Parameters.xlsx"
[1] "Selected path to IceR output: D:/20221004_2022-09-21_Otsuka_Tamara_Voelkerer_TurboID_18x/IceR_test/"
[1] "Selected IceR output name: _IceR_analysis"
[1] "Selected path to MaxQuant output: D:/20221004_2022-09-21_Otsuka_Tamara_Voelkerer_TurboID_18x/combined/txt/"
Error in stringr::str_split(data_protein$Gene_Name, ";", simplify = T)[,  : 
  subscript out of bounds

**Comment by mathiaskalxdorf** [comment]
Can you check that the column "Gene_Name" is present in the Proteins_quantification_xxx.tab files? Was there any warning in the console while IceR was running? You only posted the last few entries but there might have been a warning that some columns were missing in the input data. Further, which version of IceR were you using? It is displayed at the beginning of the Console log when you started IceR. Otherwise, you can continue your analysis by looking into the Proteins_quantification.xxx.tab (most likely most interesting is the LFQ version) file. It contains the proteins plus quantifications per sample so you can continue as if you would work with MaxQ results.
