### ISSUE TITLE
Error in gam.reparam

### ISSUE THREAD

**Issue by Angrist75** [mathiaskalxdorf/IceR#4]
dear developers
everything seemed to be working at its best then after a day of data processing the following message appeared and the shinny app IceR shut down.
Warning: Error in gam.reparam: NA/NaN/Inf in foreign function call (arg 3)
  2: shiny::runApp
  1: runIceR
please help me!
all the best 
Andrea

**Comment by mathiaskalxdorf** [comment]
Hi Andrea,
I would need some more details to clarify the issue. Can you post the complete console output from the IceR run please? Otherwise I can only guess that the error is happening during RT alignment using the gaussian additive models which are used 1.) in the beginning of the run to model the RT deviations between samples and 2.) in the middle of the run to model decoy feature intensities over RT per sample. I guess the error might happen at the second point (would also fit as you mentioned the error happened after day). Can you confirm this?

**Comment by Angrist75** [comment]
Dear Mathias
Unfortunately I didn't save the error but I could process the MQ output again with IceR. I have a doubt, the data was acquired in high resolution HCD, but in the library (used to increase the number of proteins identified with MBR) I also have data in low resolution HCD (Ion trap), could this be a problem? 
all the best 
Andrea

**Comment by mathiaskalxdorf** [comment]
Hey,
we did not test IceR yet on such scenarios so it is possible that this is causing the problem. Further, if I understand you correctly then you have your samples of interest plus library samples (most likely originating from some sort of sample fractionation)? So far we did not tested IceR for data sets with additional library (fractionated) samples but it is on our to-do list. So the problem might also arise due to these library samples. Still, I have a rough guess where the error can happen in the code but the console output would be very helpful. Similarly, the pdfs "QC_plots_IceR_analysis.pdf", and "Decoy feature quantification parameters.pdf" generated in the Temporary_files folder could be informative (consider closing the printing device after the code crashes using dev.off()). 
Best,
Mathias

**Comment by Angrist75** [comment]
I thought so...then I'll try to process only the files that interest me without the library and then I'll relaunch IceR. How important is it not to select the feature "require MS/MS for LFQ comparisons" in MQ? Is it important not to select other special features such as the "Match unidentified features" option?
thanks again for the help
Andrea

**Comment by mathiaskalxdorf** [comment]
We so far always only used MaxQ data with "require MS/MS for LFQ comparisons" switched off, but it should not influence the IceR run. Same for "Match unidentified features", so far we always kept it off, but it should not influence the IceR run except that it somehow influences the structure/format of the reported result files from MaxQuant.
Best Mathias
