### ISSUE TITLE
Could not find msconvert.exe

### ISSUE THREAD

**Issue by sshankha** [mathiaskalxdorf/IceR#5]

**Comment by mathiaskalxdorf** [comment]
Hey, 
as stated in the installation instructions, the default settings should be used during installation of ProteoWizard (msconvert). IceR currently uses a fixed location where it expects the msconvert.exe. If it can not find it there, it will ask the user to specify the path to it. However, it is not storing this information across runs yet (it will always ask again for it). Currently suggested solution: Reinstall ProteoWizard and keep default settings so that it is installed in the expected location. I will try to fix this issue with some of the next versions.

**Comment by mathiaskalxdorf** [comment]
Please install ProteoWizard with default installation parameter. In this case msconvert.exe is stored in the folder where IceR expects it. Currently IceR is only searching for it in this one folder. Otherwise the user has to always manually specify the path to msconvert.exe. We will try to make it less strict in the future.
